@if(setting('two_factor'))
<div class="card card-form" id="2fa">
    <div class="card-header">
        <h4><i class="fas fa-shield-alt"></i> @lang('Two-step authentication')</h4>
    </div>

    <form id="profile-two-factor-form" method="post">
        <div class="card-body">

            @if(auth()->user()->present()->isRecoveryLogged)
                <div class="alert alert-warning">
                    @lang('Having trouble with two-factor authentication? Update your two factor settings now.')
                </div>
            @endif

            <div class="row 2fa-content">
                
                <div class="col-12 col-md-12 2fa-wrapper-status">
                    <p id="2fa-status"><i class="fas {{ auth()->user()->present()->twoFactorStatusIcon }} {{ auth()->user()->present()->twoFactorStatusIconColor }}"></i> @lang('Two-step authentication is') {{ auth()->user()->present()->twoFactorStatus }}.</p>
                </div>

                @if(auth()->user()->present()->twoFactorStatus == 'on')
                    <div class="col-12 col-md-12 mt-3">
                        <h6>@lang('Primary method')</h6>
                        <p><i class="fas fa-mobile-alt"></i> <a href="https://authy.com/" target="_blank"><b>Authy</b></a> @lang('authenticator is enabled.')<a href="javascript:void(0)" class="float-right" title="@lang('Disable Google Authenticator')" id="btn-disable-2fa">@lang('Disable')</a></p>
                    </div>
                @else
                    <div class="col-12 col-md-12 mt-3">
                        <p class="2fa-off-intro">@lang("Two-factor authentication (2FA) is an extra layer of security for your :app_name account. In addition to your email and password to log in, you'll enter a security code generated by :authy. You must install the application to your phone.", ['app_name' => "<b>$appName</b>",'authy' => '<a href="https://authy.com/" target="_blank"><b>Authy</b></a>'])</p>
                    </div>
                    @include('profile::partials.security-sections.partials.enable-2fa-form')
                @endif

            </div>
        </div>

        @if(auth()->user()->present()->twoFactorStatus == 'off')
            <div class="card-footer bg-whitesmoke">
                <button class="btn btn-primary btn-lg float-right" type="submit" {{ auth()->user()->present()->twoFactorDisabled }}>@lang('Enable Two Factor')</button>
            </div>
        @endif
        
    </form>

</div> 
@endif

@section('modals')
    @include('profile::partials.modals.2fa-download-recovery-codes')
@endsection